### ISSUE TITLE
URL parsing

### ISSUE THREAD

**Issue by r37r05p3C7** [p0058781/AVNGameLauncher#21]
Your ui says "F95 Game Thread URL or ID"
![image](https://github.com/p0058781/AVNGameLauncher/assets/153987701/06d5c8bf-5617-4253-b276-5677f6c7ee85)

But code expects thread id only?
https://github.com/p0058781/AVNGameLauncher/blob/7162b4aada8a2a3a2ce52a10ff9a474f459c686b/sharedApp/src/commonMain/kotlin/org/skynetsoftware/avnlauncher/ui/viewmodel/ImportGameScreenModel.kt#L53-L59
https://github.com/p0058781/AVNGameLauncher/blob/7162b4aada8a2a3a2ce52a10ff9a474f459c686b/sharedApp/src/commonMain/kotlin/org/skynetsoftware/avnlauncher/ui/screen/import/ImportGameDialog.kt#L69-L76

Should be trivial to fix with simple regex, see https://github.com/Willy-JL/F95Checker/blob/d22dd272f9e6c804abd1be86342569fa128c1f93/modules/utils.py#L245

**Comment by p0058781** [comment]
It works with both actually, the code could use a cleanup though, it is not clear as you have noticed how it works
So basically `val threadId = it.toIntOrNull() ` will return null if value is not integer (not threadId)
and then below we check if it is null or not and then call appropriate function in GameImport class
https://github.com/p0058781/AVNGameLauncher/blob/7162b4aada8a2a3a2ce52a10ff9a474f459c686b/sharedApp/src/commonMain/kotlin/org/skynetsoftware/avnlauncher/data/GameImport.kt#L17-L27
