### ISSUE TITLE
crash when picking games dir on linux (filekit)

### ISSUE THREAD

**Issue by p0058781** [p0058781/AVNGameLauncher#91]
mp file picker was replaced with filekit, but file kit doesnt yet support picking directories on linux

**Comment by vinceglb** [comment]
Hi @p0058781! Actually, there is an open PR in FileKit from Snd-R to improve the support of Linux and it brings the possibility to pick directories: https://github.com/vinceglb/FileKit/pull/65

I will soon review the PR. It will probably fix your issue?

**Comment by p0058781** [comment]
Awesome, thank you for letting me know

**Comment by vinceglb** [comment]
[Version 0.7.0](https://github.com/vinceglb/FileKit/releases/tag/0.7.0) is out improving Linux support 👌

**Comment by p0058781** [comment]
@vinceglb 
Well, in my linux setup (arch + sway) i didn't have xdg-desktop-portal, and it could be the case for other linux users as well, so i decided to make a PR to introduce Swing JFileChooser as a fallback for directory picking that works always
https://github.com/vinceglb/FileKit/pull/70

**Comment by p0058781** [comment]
Decided to implement super simple built in file picker that just uses JFileChooser. This project isn't really multiplatform (onli jvm supported) so no need to use external library. JFileChooser is ugly but i dont care at this point.
